bitsoex/slate

source/index.html.md

Add generic crypto_withdrawal endpoint

---

source/index.html.md

relevant to https://github.com/bitsoex/bitsoex/pull/946

revert rogue receive spelling change

---

source/index.html.md

Changes param name and son response for webhooks. 
Will link this to corresponding PR on bitsoex.

LIL webhooks small update

---

source/index.html.md

Add 0202 error code
Signed-off-by: Victor <victor.cruz.isc@gmail.com>

Add 0202 error code

---

source/index.html.md

See also https://github.com/bitsoex/bitsoex/pull/1371 and https://github.com/bitsoex/bitsoex/pull/1372

Add error codes to slate documentation

---

source/index.html.md

error code(0339) for email is already in use

Email is already in use

---

source/index.html.md

EXO-504 Add some specific errors for unverified accounts

---

source/index.html.md

Add 0802 error "Too many attempts to perform an operation"

---

source/index.html.md

Add docs for filtering by status & method, and pagination

Add documentation for withdrawal API improvements

---

source/index.html.md

CORE-987
See https://github.com/bitsoex/bitsoex/pull/1737

Update API docs for deposit filtering and pagination

---

source/index.html.md

See https://github.com/bitsoex/bitsoex/pull/1894

Add docs for specifying the maximum withdrawal fee

---

source/index.html.md

Update our api documents about rate limiting

CORE-1100 Modify our api rate limit docs

---

source/index.html.md

Add new error code for not defined legal operation entity

---

source/index.html.md

CORE-1196 Add error to request agreeing latest TOS

---

source/index.html.md

0900 error indicates that no lookup was found with the given
hash.

CORE-1102 Add 0355 Error code

---

source/index.html.md

Cancellations not subject of rate rate limiting
time in force field when placing an order

Core cancel time in force

---

source/index.html.md

Also fix the response for a couple of order related
messages
CORE-1321

Update slate documentation for postonly orders and client_id param

---

source/index.html.md

CORE-1410 Add specific error for disabled feature due user optout

---

source/index.html.md

CORE-1624 Fix typo

---

source/index.html.md

CORE-1582 New error code 0408 amount must be positive

---

source/index.html.md

Please note 0357 is in use in another PR which will be added later on

Added password length error codes

---

source/index.html.md

See https://github.com/bitsoex/bitsoex/pull/2855 for PHP side

Added Misc errors, including API temporarily disabled (1000)

---

source/index.html.md

CORE-1625 Add keep alive messages definition

---

source/index.html.md

CORE-1161 Add some error codes and get rid of client_id field

---

source/index.html.md

Error codes 0360 and 0361 are being used in - https://github.com/bitsoex/slate/pull/46

CORE-1682 Add specific error codes to handle callback URL errors

---

source/index.html.md

Add error code 0345 for Quote is expired or invalid

Add error code 0345

---

source/index.html.md

PYMT-662 Add error code and operation errors

---

source/index.html.md

Added `maker-side` attribute to the order object.

CORE-1640: Add maker side field to orders

---

source/index.html.md

PHP side - https://github.com/bitsoex/bitsoex/pull/3004

Added new error code for invalid transaction ID when performing a lookup by transaction ID

---

source/index.html.md

IFPEPROD-224 Add password error codes

---

source/index.html.md

Add required error codes for handling enable/disable 2FA

---

source/index.html.md

See https://github.com/bitsoex/bitsoex/pull/3705

Added errors coming from Twilio

---

source/index.html.md

See https://github.com/bitsoex/bitsoex/pull/3766 for usage reference

BITA-616 Add error code 1005 Invalid operation

---

source/index.html.md

Also fixed a glaring error in a sentence :scream:

Added instructions about the txids parameters in the Fundings endpoint

---

source/index.html.md

Add error code 0710

---

source/index.html.md

[There should not be two or more beneficiaries with the same name and relationship](https://bitsomx.atlassian.net/browse/IFPEPROD-980)
- Adding error codes **0712, 0713 & 0714** - decided to go with those codes due to pending PR's which are adding other codes in the same block. 
- [IFPEPROD-980: user beneficiaries validations](https://github.com/bitsoex/bitsoex/pull/3815)

IFPEPROD-980: User beneficiaries validations (error codes doc)

---

source/index.html.md

this new error code will replace the usage of the [wrong error code](https://bitsomx.atlassian.net/browse/CORE-2154)

Add error code 0711

---

source/index.html.md

Change month

---

source/index.html.md

Required error for correct handling of devices.
PHP PR - https://github.com/bitsoex/bitsoex/pull/4109

BITA-464 Add error code 0369 "Invalid device id"

---

source/index.html.md

required errors for file validations
related pr: https://github.com/bitsoex/bitsoex/pull/3869

IFPEPROD-900 file validation error codes

---

source/index.html.md

[API endpoint for business persons](https://bitsomx.atlassian.net/browse/IFPEPROD-571)
* Added the following codes: 
- 0715: Error saving users business person(s)
- 0716: Error fetching users business person(s)
- 0717: Incorrect value for users business persons(s) types
- 0718: User business person doesn't belongs to the user
- 0372: Incorrect value type for field
Bitsoex PR: https://github.com/bitsoex/bitsoex/pull/4151

IFPEPROD-571: User business person error codes

---

source/index.html.md

- [Update GET /app_recall endpoint for old mobile versions](https://bitsomx.atlassian.net/browse/BITA-1550)
* Well we need an error code to express when there are errors when reading the `app_recall/config.json`

BITA-1550: New error codes for App recall

---

source/index.html.md

In order to retrieve better error messages, QA & Product design team suggest to change the error message when a token is expired/not found in the new reset password flow.
Error message: https://github.com/bitsoex/bitsoex/pull/4546/files#diff-237a1a402fb5a39a930648f2cabd29475168243ed123a2dcf994affee8f98d81R2779
[BITA-1578](https://bitsomx.atlassian.net/browse/BITA-1578)
[BITA-1879](https://bitsomx.atlassian.net/browse/BITA-1879)

Bita 1578 - Reset password flow new error code

---

source/index.html.md

- [BITA-1766: Block and unblock my withdrawals - Backend](https://bitsomx.atlassian.net/browse/BITA-1766)
- [BITA-2003: Block my account - Backend](https://bitsomx.atlassian.net/browse/BITA-2003)
- [Internal API Doc](https://bitsomx.atlassian.net/wiki/spaces/EXCH/pages/803569771/Internal+API+documentation#security_actions---php-(WIP))
- Adds new error code `0721` to specify any error after trying to perform any security action (i.e. block withdrawals)

BITA-2003 & BITA-1766: new error code for security_actions endpoint

---

source/index.html.md

[BITONBO-444](https://bitsomx.atlassian.net/browse/BITONBO-444)
This error code can be used with other `kyc` fields other than just `CURP`

BITONBO 444: Generalize KYC error

---

source/index.html.md

Just a quick update for future usability of these codes for other KYC documents

Updating KYC documentation for errors

---

source/index.html.md

Device usage tracking specific errors for login and sign-up

ITOOLS-419 Errors description

---

source/index.html.md

New code added: `0374: Invalid 2FA recovery code`

BITA-2380 - Added new code

---

CHANGELOG.md
source/index.html.md

PR - Fix inconsistency between WS API and its docs
Jira Task: https://bitsomx.atlassian.net/browse/AS2-51
This PR contains the following features:
- API inconsistency fix for diff-orders and orders "t" field
- Implementation of this API can be verified here: [bitso-websockets](https://github.com/bitsoex/bitso-websockets/blob/7d97d1c3cf909f544b5f9fb89e23dc844439884b/api.js#L365)

[AS2-51] api inconsistency fix for diff-orders and orders

---

source/index.html.md

https://bitsomx.atlassian.net/browse/BITWA-1288
https://bitsomx.atlassian.net/browse/BITWA-1285
Just add a new error code that is returned when an action is restricted for a business account
Used in: https://github.com/bitsoex/bitsoex/pull/5417

BITWA-1288 Add new error code

---

CHANGELOG.md
source/index.html.md

Updating the value for the status key as explained in this story [Jira Issue](https://bitsomx.atlassian.net/browse/AS2-88)

AS2-88: Fix value of status field

---

source/index.html.md

Added new error message for bitso shift share wire instructions feature

BSHIFT-386: Added new error message

---

source/index.html.md

Point to sandbox environment in the Developer Testing server section.

CLD-576: Point dev api to sandbox

---

source/index.html.md

This pull request adds documentation for a new error code which indicates that an ip address is restricted from accessing a resource

Add slate docs for new ip restriction error code

---

CHANGELOG.md
source/index.html.md

PR - Review fix open_orders request parameters.
Jira Task: https://bitsomx.atlassian.net/browse/AS2-325
This PR contains the following features:
- some minimal documentation fix.

[AS2-325] open_orders documentation fix

---

CHANGELOG.md
source/index.html.md

Implemented here: https://github.com/bitsoex/bitsoex/pull/6081

New error code for bitso transfer limit

---

CHANGELOG.md
source/index.html.md

Please refer to [XP-1515](https://github.com/bitsoex/bitsoex/pull/6208) for the code 1008
Code 1009 will be implemented in the next sprint

XP-1515 and XP-1520 - Adding error messages for disabled functionalities

---

source/index.html.md

Adding error codes for OTP flow

Adding OTP error codes

---

CHANGELOG.md
source/index.html.md

Deleting `Invalid Nonce or Invalid Credentials`
New messages:
ENG: Check your credentials
SP-MX: Verifica tus credenciales
SP-AR: Verificá tus credenciales
PT-BR: Confira suas credenciais

AITE-78: Update "Invalid nonce or credentials" message

---

CHANGELOG.md
source/index.html.md

Creating a 500 error code to acknowledge currency service error.

add 500 currency service error

---

CHANGELOG.md
source/index.html.md

FE is using this code to know the status of the validation in the ubo/directors list.

BUSIACC-2027 add new business validation error code

---

source/index.html.md

- Added missing withdrawal metadata docs.
- Added missing withdrawal endpoint docs.
- Added new error code documentation.

added withdrawals docs
